### PR TITLE
Emscripten-enabled psgplay

### PR DESCRIPTION
**Pull request by tin-nl**
I recenty did some tests to embed psgplay into gasman's/demozoo's pretty cool cowbell player. 

To be able to build psgplay via emscripen an to embed it into cowbell I needed a) a single library to be built and b) a distinction between host tooling (as in: tools that are built and are meant to be run on the build host) and the target built (emscripten in this case).

This is what me and my non-existing makefile-knowledge came up with. Feel free to correct my (prbly totally horrendous) approach. It would be great if a way to build psgplay via emscripten could find it's way upstream.

Have a look at at psgplay in action _inside_ of cowbell: https://absencehq.de/atari/tmp/psgplay/example/

And just FYI here's how I hacked the emscriptened psgplay into cowbell itself: https://github.com/tin-nl/cowbell/commits/master (see Makefile target libpsgplay at the end of the file)

Let me know if I can do things better/cleaner etc.

### CODE REVIEW

**Comment by frno7** [comment]
Oh, nice, @tin-nl. Let’s make this work. I’ve been thinking about improving the makefiles for some time.

There’s a `CROSS_COMPILE` variable, but it’s intended for compiling the (optional) m68k code. Maybe we could get rid of `CROSS_COMPILE`, for a cleaner split between _host_ (build) and _target_ compilers. Let me have a look at it.

I’m considering adopting more [GNU Makefile conventions](https://www.gnu.org/software/make/manual/html_node/Makefile-Conventions.html) such as, for instance, adding proper `install` targets.

Also, this `psgplay` repo should probably be split into [Git submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules). The [`lib/toslibc`](https://github.com/frno7/psgplay/tree/master/lib/toslibc) directory, for instance, already has a proper [`toslibc`](https://github.com/frno7/toslibc) repo on its own these days.

**Comment by tin-nl** [comment]
Sounds very good!

The nice thing about emscripten is, that it's basically a drop-in replacement for the whole make/gcc chain - e.g. building a make-base project via
`emmake make`
wraps the make call and redirects e.g. the `CC` env variables to emcc instead of gcc etc. and thus there's no special cross-compile environment _needed_ for the project to be ported (altho it could be done using emcc directly as far as I've seen).  This is the _theory_ and it does ofc has it's corner cases. But with a bit of fiddling even complex stuff like http://absencehq.de/atariaviary/ is running pretty well.

In my humble emscripten-y psgplay approach I just called the host build w/o emscripten wrappers and the lib _with_ the wrappers - that's ofc a very weak approach, because in my implementation inside the _cowbell_ makefile makes those calls and decisions, which is... well... not good.

Fortunately cowbell is (kinda almost) containerized (it uses vagrant). So cowbell's build fares pretty well as a testcase if you want to get an emscripten env running I'd think. Installing it manually isn't too involved either, but takes much longer.

**Comment by frno7** [comment]
I’ve just pushed a series of commits for proper Makefile `install` targets, along with a [SONAME](https://en.wikipedia.org/wiki/Soname) for the shared library, and a [pkg-config](https://en.wikipedia.org/wiki/Pkg-config) file.

My plan is to add `BUILD_CC`, `HOST_CC`, and `TARGET_CC` variables to the Makefile. They seem to be quite common with packages similar to this one, in dealing with the (at most) three architectures involved.

In this repo `TARGET_CC` (corresponding to the current `CROSS_COMPILE` variable) is always m68k, to compile code for the Atari ST. It’s needed to build `PSGPLAY.TOS`, or to rebuild [`lib/tos/tos`](https://github.com/frno7/psgplay/blob/master/lib/tos/tos) (the boot ‘ROM’ file) which for convenience has been precompiled in the repo. For most people, `TARGET_CC` is therefore optional. The _target_ is the m68k architecture fundamentally being emulated, in every case.

In the present case, `HOST_CC` would be an [Emscripten](https://en.wikipedia.org/wiki/Emscripten) compiler, whereas `BUILD_CC` would be a compiler for whatever machine one is using to build the package (in my case [POWER9](https://en.wikipedia.org/wiki/POWER9), but [x86-64](https://en.wikipedia.org/wiki/X86-64) is otherwise common for Linux, and recently [ARM](https://en.wikipedia.org/wiki/ARM_architecture_family) for Mac OS, and so on). The _host_ is the architecture performing (running) the emulation, which often but not always is the same as the _build_ architecture.

**Comment by frno7** [comment]
The `BUILD_CC`, `HOST_AR`, `HOST_CC`, and `TARGET_CC` with `TARGET_LD` Makefile variables can now be configured for various cross-compilation settings. The `BUILD_CFLAGS`, `HOST_CFLAGS`, `TARGET_CFLAGS`, and `TARGET_LDFLAGS` are available as well. The Makefiles should now cleanly separate build and host objects, as opposed to previously.

I haven’t tested Emscripten yet, but `make HOST_CC=mipsr5900el-unknown-linux-gnu-gcc psgplay` successfully cross-compiles a MIPS/R5900 host program, on a POWER9 build system, for instance.

**Comment by tin-nl** [comment]
Wow, thanks!

I got it (kinda) working; since I need the unice-routs in libpsgplay, I had to add sth clumsy like
`$(LIBPSGPLAY_EMSCRIPTEN): $(LIBPSGPLAY_OBJ) $(patsubst %.c, %.o, $(ICE_SRC))
	$(QUIET_CC)$(CC) $(SOFLAGS) -o $@ $^`
to the main Makefile.

now I get the whole thing to build along the lines of
`emmake make LIBPSGPLAY_EMSCRIPTEN=libpsgplay.js SOFLAGS="<loads of emscripten specific linking things here>" HOST_CC=emcc HOST_AR=emar BUILD_CC=gcc libpsgplay.js`

I guess it's maybe probably a good idea to add a emscripten specific target? Ofc cowbell _can_ define what functions libpsgplay exports, but it's prbly not the best place for that decision.

**Comment by frno7** [comment]
Take a look at the experimental [`emscripten`](https://github.com/frno7/psgplay/tree/emscripten) branch. :-) I made Ice decompression available in commit 94eebc476f4f2d0b0effed0a5abae80ba6632422 and `$(LIBPSGPLAY_JAVASCRIPT)` and `$(LIBPSGPLAY_WEBASSEMBLY)` targets in commit a5be23dfc75eaacb9eebe5f6074e76e32c9de75c. Then try something like

```
make HOST_CC=emcc lib/psgplay/libpsgplay.js
```

to obtain both `lib/psgplay/libpsgplay.js` and `lib/psgplay/libpsgplay.wasm`. I made

https://github.com/frno7/psgplay/blob/a5be23dfc75eaacb9eebe5f6074e76e32c9de75c/lib/psgplay/Makefile#L9-L24

to generate `EXPORTED_FUNCTIONS`, etc.

I haven’t decided whether to call the variable `HOST_WEBFLAGS`. Maybe simply `WEBFLAGS` is better.

**Comment by tin-nl** [comment]
Works like a charm! :) Thanks alot.

Lib size even halved when build with -O2 compared to my hackery.

**Comment by frno7** [comment]
Bliss! The [`HEAD`](https://github.com/frno7/psgplay) branch is now updated. There’s now a new `web` target, so one can simply do `make HOST_CC=emcc web`, and some minor clean-ups. The experimental [`emscripten`](https://github.com/frno7/psgplay/tree/emscripten) branch will be removed, eventually.

**Comment by tin-nl** [comment]
Bliss indeed \o/ Emscripten's now a thing in psgplay in a proper way, so I think we can close this.

**Pull request closed without merging**
